/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx,html}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#09141e",
        "surface-dim": "#09141e",
        "surface-bright": "#2f3a45",
        "surface-container-lowest": "#050f18",
        "surface-container-low": "#121d26",
        "surface-container": "#16212b",
        "surface-container-high": "#202b35",
        "surface-container-highest": "#2b3640",
        "on-surface": "#d8e4f1",
        "on-surface-variant": "#bbcbbb",
        "inverse-surface": "#d8e4f1",
        "inverse-on-surface": "#27323c",
        "outline": "#869486",
        "outline-variant": "#3d4a3e",
        "surface-tint": "#4ae183",
        "primary": "#54e98a",
        "on-primary": "#003919",
        "primary-container": "#2ecc71",
        "on-primary-container": "#005027",
        "inverse-primary": "#006d37",
        "secondary": "#ffb961",
        "on-secondary": "#472a00",
        "secondary-container": "#e89300",
        "on-secondary-container": "#563400",
        "tertiary": "#a3d3ff",
        "on-tertiary": "#003351",
        "tertiary-container": "#5fbaff",
        "on-tertiary-container": "#004970",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#6bfe9c",
        "primary-fixed-dim": "#4ae183",
        "on-primary-fixed": "#00210c",
        "on-primary-fixed-variant": "#005228",
        "secondary-fixed": "#ffddb9",
        "secondary-fixed-dim": "#ffb961",
        "on-secondary-fixed": "#2b1700",
        "on-secondary-fixed-variant": "#663e00",
        "tertiary-fixed": "#cce5ff",
        "tertiary-fixed-dim": "#92ccff",
        "on-tertiary-fixed": "#001d31",
        "on-tertiary-fixed-variant": "#004b73",
        "background": "#09141e",
        "on-background": "#d8e4f1",
        "surface-variant": "#2b3640",
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "2xl": "1.75rem",
        "3xl": "2rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "xs": "4px",
        "sm": "12px",
        "md": "24px",
        "lg": "40px",
        "xl": "64px",
        "gutter": "16px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        sans: ["Quicksand", "sans-serif"],
        headline: ["'Plus Jakarta Sans'", "sans-serif"],
        body: ["Quicksand", "sans-serif"],
        "display-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-lg-mobile": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["Quicksand", "sans-serif"],
        "body-md": ["Quicksand", "sans-serif"],
        "label-xl": ["Quicksand", "sans-serif"],
      },
      boxShadow: {
        'chunky-sm': '0 4px 0 0 rgba(0,0,0,0.3)',
        'chunky-md': '0 8px 0 0 rgba(0,0,0,0.4)',
        'chunky-lg': '0 12px 0 0 rgba(0,0,0,0.5)',
      }
    },
  },
  plugins: [],
}
